#!/bin/bash

# SPDX-FileCopyrightText: none
#
# SPDX-License-Identifier: CC0-1.0

# Get the version we're releasing
version=$(git describe)
version=${version##*v}

# Create snapshot
mkdir gpx2svg-$version
git archive HEAD | tar -xC gpx2svg-$version
cd gpx2svg-$version

# Update the project version
sed -i -e "s/@VERSION@/$version/" gpx2svg

# Remove the "make_release" script
rm make_release

# Create the release tarball
cd ..
tar -cJf gpx2svg-$version.tar.xz gpx2svg-$version
rm -r gpx2svg-$version
